server:
  port: 8081

spring:
  datasource:
    # Correto para o Docker acessar o banco no seu Windows
    url: jdbc:postgresql://host.docker.internal:5432/company001
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          descriptor:
            sql:
              format_binary: true
        jdbc:
          lob:
            non_contextual_creation: true
  web:
    error:
      include-message: always
      include-stacktrace: always
  main:
    allow-bean-definition-overriding: true
