spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/company001
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
